//! `fsio` — all filesystem reads (loading `rules/*.md`) and writes (emitting
//! target files), including the generated-file guard that refuses to overwrite
//! a target lacking the generated-by header and matching hash
//! (`[R:generate-guards-unversioned]`).
//!
//! **Must NOT:** contain business logic. It moves bytes and prepends file names
//! to diagnostics; every decision about *what* a document means is made in
//! `rule` (parsing) and every decision about *what* to write is made in `emit`.

use std::collections::BTreeSet;
use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::emit::{OutputFile, RelativePath};
use crate::library::{Library, Unvalidated};
use crate::rule::{ParseError, parse_document};

/// The opening of the generated-by comment. Its presence in an existing file is
/// how the overwrite guard tells "relearn wrote this" from "a human wrote this":
/// a file carrying it may be regenerated; a file lacking it is never clobbered
/// (`[R:generate-guards-unversioned]`). An HTML comment is valid in every
/// current target (all markdown-family) and, placed after the body, never
/// disturbs the leading YAML front-matter of a skill or `.mdc`.
const GENERATED_MARKER: &str = "<!-- relearn:generated";

/// Why loading a rules directory failed. Every variant names the file (or
/// directory) at fault, so a diagnostic points the operator straight at it.
#[derive(Debug, thiserror::Error)]
pub enum LoadError {
    /// The rules directory could not be read.
    #[error("reading directory {path:?}: {source}")]
    ReadDir {
        /// The directory that could not be read.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A rule file could not be read.
    #[error("reading {path:?}: {source}")]
    Io {
        /// The file that could not be read.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A rule file was read but did not parse. Carries the field-level
    /// `ParseError` and the file it came from — the "file + field" diagnostic.
    #[error("{path:?}: {source}")]
    Parse {
        /// The file that failed to parse.
        path: PathBuf,
        /// The field-level parse error.
        #[source]
        source: ParseError,
    },
}

/// Load every `*.md` file in `dir` into an unvalidated library, in sorted file
/// order for determinism. A file that cannot be read or parsed stops the load
/// with a diagnostic naming it — a bad file is never silently skipped.
///
/// The result is `Library<Unvalidated>`; the caller runs `validate` to check
/// cross-file invariants (tag uniqueness) and reach `Library<Validated>`.
pub fn load_rules(dir: &Path) -> Result<Library<Unvalidated>, LoadError> {
    let read = fs::read_dir(dir).map_err(|source| LoadError::ReadDir {
        path: dir.to_path_buf(),
        source,
    })?;

    let mut paths: Vec<PathBuf> = Vec::new();
    for entry in read {
        let entry = entry.map_err(|source| LoadError::ReadDir {
            path: dir.to_path_buf(),
            source,
        })?;
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "md") {
            paths.push(path);
        }
    }
    paths.sort();

    let mut library = Library::new();
    for path in paths {
        // `path` is moved into the error on either failure path and dropped on
        // success — so it is never cloned.
        let content = match fs::read_to_string(&path) {
            Ok(content) => content,
            Err(source) => return Err(LoadError::Io { path, source }),
        };
        let rule = match parse_document(&content) {
            Ok(rule) => rule,
            Err(source) => return Err(LoadError::Parse { path, source }),
        };
        library.push(rule);
    }
    Ok(library)
}

/// Why writing emitted files failed. Every variant names the file at fault.
#[derive(Debug, thiserror::Error)]
pub enum WriteError {
    /// A parent directory could not be created.
    #[error("creating directory {path:?}: {source}")]
    CreateDir {
        /// The directory that could not be created.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A file could not be read (during the pre-flight check) or written.
    #[error("{path:?}: {source}")]
    Io {
        /// The file at fault.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// The target file already exists and does not carry relearn's generated-by
    /// marker, so it is unversioned, human-authored content. The guard refuses
    /// to overwrite it rather than destroy a correction that was never a rule.
    #[error(
        "{path:?} exists but was not generated by relearn (no generated-by marker); refusing to overwrite unversioned content"
    )]
    WouldClobberUnversioned {
        /// The file that would have been clobbered.
        path: PathBuf,
    },
}

/// Write every emitted file under `out_dir`, each with its generated-by header
/// and content hash appended.
///
/// All-or-nothing over the clobber guard: a **pre-flight** pass checks every
/// target first, and if any existing target lacks the generated-by marker the
/// whole write aborts with [`WriteError::WouldClobberUnversioned`] before a
/// single byte is written — so one human-authored collision never leaves a
/// half-generated tree. Returns the number of files written.
#[must_use = "the write result reports failure (clobber refusal, I/O); ignoring it discards that"]
pub fn write_all(out_dir: &Path, files: &[OutputFile]) -> Result<usize, WriteError> {
    // Pre-flight: refuse the entire write if any target is unversioned content.
    for file in files {
        let target = out_dir.join(file.path().as_str());
        match fs::read(&target) {
            Ok(existing) => {
                if !contains_marker(&existing) {
                    return Err(WriteError::WouldClobberUnversioned { path: target });
                }
            }
            // Absent target is the normal case — it will be created below.
            Err(source) if source.kind() == ErrorKind::NotFound => {}
            Err(source) => {
                return Err(WriteError::Io {
                    path: target,
                    source,
                });
            }
        }
    }

    // Commit: every target is either new or one we previously generated.
    for file in files {
        let target = out_dir.join(file.path().as_str());
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent).map_err(|source| WriteError::CreateDir {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        let rendered = render_with_header(file);
        fs::write(&target, rendered).map_err(|source| WriteError::Io {
            path: target,
            source,
        })?;
    }
    Ok(files.len())
}

/// Why verifying the generated tree failed. Absence of an expected file is *not*
/// an error (it is a [`VerifyStatus::Missing`] report); only an I/O failure that
/// is not "file not found" stops the verify.
#[derive(Debug, thiserror::Error)]
pub enum VerifyError {
    /// A target file could not be read for a reason other than absence.
    #[error("{path:?}: {source}")]
    Io {
        /// The file at fault.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
}

/// How one expected generated file compares to what is on disk. Every variant
/// but [`VerifyStatus::Ok`] is drift a `relearn verify` reports and fails on.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VerifyStatus {
    /// On disk and byte-identical to what `build` would write from the current
    /// rules — no drift.
    Ok,
    /// `build` would write this file, but it is absent from disk.
    Missing,
    /// A file occupies the path but carries no generated-by marker: hand-authored
    /// content where a generated file would go. `build` would refuse to overwrite
    /// it; `verify` flags it rather than silently treating it as generated.
    Unversioned,
    /// Present and marked, but its body no longer hashes to the value its own
    /// header records — edited by hand since generation, so the next `build`
    /// would silently overwrite the edit.
    HandEdited,
    /// Present, marked, and internally consistent (body matches its own recorded
    /// hash), but not what the current rules (or tool version) emit — stale;
    /// regenerate with `relearn build`.
    Stale,
    /// A relearn-generated file (it carries the marker) sitting in a relearn-owned
    /// location that the current rules would NOT emit — its rule or home was
    /// removed, so `build` leaves it untouched and it lingers forever. Delete it,
    /// or restore the rule. Reported for paths NOT in the expected set, so it
    /// never overlaps the per-expected-file states above.
    Orphan,
}

impl VerifyStatus {
    /// Whether this is the no-drift state ([`VerifyStatus::Ok`]).
    #[must_use]
    pub fn is_clean(&self) -> bool {
        matches!(self, VerifyStatus::Ok)
    }
}

impl std::fmt::Display for VerifyStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let msg = match self {
            VerifyStatus::Ok => "up to date",
            VerifyStatus::Missing => "missing — expected but not on disk; run `relearn build`",
            VerifyStatus::Unversioned => {
                "unversioned — a non-generated file occupies this path; `build` would refuse it"
            }
            VerifyStatus::HandEdited => {
                "hand-edited — body no longer matches its recorded hash; the next `build` would overwrite the edit"
            }
            VerifyStatus::Stale => {
                "stale — does not match the current rules; run `relearn build` to regenerate"
            }
            VerifyStatus::Orphan => {
                "orphan — a relearn-generated file whose rule was removed; `build` will not touch it. Delete it, or restore the rule"
            }
        };
        f.write_str(msg)
    }
}

/// The verification outcome for one expected generated file: where it would be
/// written and how the on-disk reality compares.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct VerifyReport {
    path: RelativePath,
    status: VerifyStatus,
}

impl VerifyReport {
    /// The file's path relative to the output root.
    #[must_use]
    pub fn path(&self) -> &RelativePath {
        &self.path
    }

    /// How the on-disk file compares to a fresh emission.
    #[must_use]
    pub fn status(&self) -> &VerifyStatus {
        &self.status
    }
}

/// Verify — read only, never write — that the files `build` would emit under
/// `out_dir` match what is on disk: each is present, internally consistent (its
/// body still hashes to the value its own header records), and byte-identical to
/// a fresh emission. Returns one [`VerifyReport`] per expected file, in the given
/// order. This is the detection complement to [`write_all`]'s prevention: the
/// guard stops `build` clobbering human files, `verify_all` catches a generated
/// file that was hand-edited or left stale.
#[must_use = "the verify reports are the whole result; ignoring them discards every drift finding"]
pub fn verify_all(out_dir: &Path, files: &[OutputFile]) -> Result<Vec<VerifyReport>, VerifyError> {
    let expected: BTreeSet<&str> = files.iter().map(|f| f.path().as_str()).collect();

    let mut reports = Vec::with_capacity(files.len());
    for file in files {
        let target = out_dir.join(file.path().as_str());
        let status = match fs::read(&target) {
            Ok(bytes) => classify(&bytes, file),
            Err(source) if source.kind() == ErrorKind::NotFound => VerifyStatus::Missing,
            Err(source) => {
                return Err(VerifyError::Io {
                    path: target,
                    source,
                });
            }
        };
        reports.push(VerifyReport {
            path: file.path().clone(), // allow:clone: the report owns its path, outliving the &[OutputFile] borrow
            status,
        });
    }

    // Orphan pass: relearn-generated files (marker-bearing) in owned locations
    // that the current rules would NOT emit — their rule or home was removed, so
    // `build` never touches them again and they linger. Reported for paths not in
    // the expected set, so they never overlap the per-expected-file states above.
    for path in scan_orphans(out_dir, &expected)? {
        reports.push(VerifyReport {
            path,
            status: VerifyStatus::Orphan,
        });
    }
    Ok(reports)
}

/// relearn-owned directories, walked recursively for its own generated files.
/// These hold the variable per-home / per-rule targets where a removed rule can
/// strand an orphan (`skills/<slug>/SKILL.md`, `.cursor/rules/<tag>.mdc`,
/// `.claude/rules/<slug>.md`). Only files carrying the marker are ever
/// considered, so a hand-authored file here is left alone; and only these
/// subtrees are walked, so unrelated content elsewhere under the output root is
/// never inspected.
const OWNED_DIRS: &[&str] = &["skills", ".cursor/rules", ".claude/rules"];

/// relearn-owned fixed single-file targets. Each has exactly one path, so an
/// orphan arises only when the file is no longer emitted at all yet a marked
/// one lingers on disk.
///
/// The repository-root `CLAUDE.md` is deliberately **absent**: it is the
/// hand-authored project charter, and since 2026-08-22 the project layer is
/// emitted per home under `.claude/rules/` instead. Claiming the charter as an
/// owned path is the collision this repository shipped for months — see
/// `emit::claude_md` for the full account.
const OWNED_FILES: &[&str] = &["AGENTS.md", ".github/copilot-instructions.md"];

/// Find relearn-generated files (marker-bearing) under `out_dir`'s owned
/// locations whose relative path is not in `expected` — orphans. Read only, and
/// scoped to owned locations and marked files: an unrelated or hand-authored file
/// is never claimed. Sorted, for a deterministic report order.
fn scan_orphans(
    out_dir: &Path,
    expected: &BTreeSet<&str>,
) -> Result<Vec<RelativePath>, VerifyError> {
    let mut found: Vec<PathBuf> = Vec::new();
    for dir in OWNED_DIRS {
        collect_files(&out_dir.join(dir), &mut found)?;
    }
    for f in OWNED_FILES {
        let p = out_dir.join(f);
        if p.is_file() {
            found.push(p);
        }
    }

    let mut orphans: Vec<RelativePath> = Vec::new();
    for full in found {
        // The emitters' paths are forward-slash and relative to the output root;
        // normalize the discovered path the same way before comparing.
        let rel = match full.strip_prefix(out_dir) {
            Ok(r) => r.to_string_lossy().replace('\\', "/"),
            Err(_) => continue,
        };
        if expected.contains(rel.as_str()) {
            continue; // an expected path — already classified by the main loop
        }
        match fs::read(&full) {
            Ok(bytes) if contains_marker(&bytes) => {
                orphans.push(RelativePath::from_forward_slash(rel));
            }
            Ok(_) => {} // unmarked → not relearn's
            Err(source) if source.kind() == ErrorKind::NotFound => {} // vanished mid-scan
            Err(source) => return Err(VerifyError::Io { path: full, source }),
        }
    }
    orphans.sort();
    Ok(orphans)
}

/// Recursively collect regular files under `dir` into `out`. A missing directory
/// is simply empty, not an error — an output root need not contain every target.
fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), VerifyError> {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(source) if source.kind() == ErrorKind::NotFound => return Ok(()),
        Err(source) => {
            return Err(VerifyError::Io {
                path: dir.to_path_buf(),
                source,
            });
        }
    };
    for entry in entries {
        let entry = entry.map_err(|source| VerifyError::Io {
            path: dir.to_path_buf(),
            source,
        })?;
        let file_type = entry.file_type().map_err(|source| VerifyError::Io {
            path: entry.path(),
            source,
        })?;
        let path = entry.path();
        if file_type.is_dir() {
            collect_files(&path, out)?;
        } else if file_type.is_file() {
            out.push(path);
        }
    }
    Ok(())
}

/// Classify one on-disk file against the fresh emission `expected`. Precedence:
/// no marker → `Unversioned`; marker but body-hash mismatch (or a malformed
/// header) → `HandEdited`; self-consistent but not the fresh bytes → `Stale`;
/// byte-identical → `Ok`. Integrity is checked before freshness so a hand edit
/// is never mislabelled as mere staleness.
fn classify(bytes: &[u8], expected: &OutputFile) -> VerifyStatus {
    if !contains_marker(bytes) {
        return VerifyStatus::Unversioned;
    }
    // We only ever write UTF-8; a marked file that is not valid UTF-8 was mangled.
    let Ok(content) = std::str::from_utf8(bytes) else {
        return VerifyStatus::HandEdited;
    };
    let Some((body, stored_hash)) = parse_generated(content) else {
        return VerifyStatus::HandEdited;
    };
    if sha256_hex(body.as_bytes()) != stored_hash {
        return VerifyStatus::HandEdited;
    }
    if content == render_with_header(expected) {
        VerifyStatus::Ok
    } else {
        VerifyStatus::Stale
    }
}

/// Split a generated file into its body and the `sha256` its header records.
/// `None` if the marker is absent, is not preceded by the separator newline the
/// renderer writes, or the header has no `sha256=` field — any of which means
/// the file is not a well-formed relearn artifact and the caller treats it as
/// hand-edited.
fn parse_generated(content: &str) -> Option<(&str, &str)> {
    let marker_pos = content.rfind(GENERATED_MARKER)?;
    // The renderer writes `{body}\n{header}\n`, so the marker is always preceded
    // by the separator newline; the body is everything before that newline.
    let separator = marker_pos.checked_sub(1)?;
    if content.as_bytes().get(separator) != Some(&b'\n') {
        return None;
    }
    let body = &content[..separator];
    let header = &content[marker_pos..];
    let hash = header.split("sha256=").nth(1)?.split(' ').next()?;
    if hash.is_empty() {
        return None;
    }
    Some((body, hash))
}

/// Append the generated-by header (marker, tool version, source-rule tags, and
/// the `sha256` of the body) to a file's body. The hash covers the body only —
/// not the header — so it can later be recomputed and compared to detect a hand
/// edit of a generated file.
fn render_with_header(file: &OutputFile) -> String {
    let hash = sha256_hex(file.contents().as_bytes());
    let rules = file
        .sources()
        .iter()
        .map(|tag| tag.as_str())
        .collect::<Vec<_>>()
        .join(",");
    // ASCII-only: this marker is embedded into every emitted file and parsed by
    // several downstream tools; it must not depend on their encoding assumptions.
    let header = format!(
        "{GENERATED_MARKER} v{version} sha256={hash} rules={rules} -- DO NOT EDIT; regenerate with `relearn build` -->",
        version = env!("CARGO_PKG_VERSION"),
    );
    format!("{body}\n{header}\n", body = file.contents())
}

/// Hex-encode the SHA-256 of `bytes`.
fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Whether `bytes` contains the generated-by marker anywhere. Byte-level (not
/// UTF-8) so a non-text or invalid-UTF-8 existing file is simply treated as
/// unversioned (marker absent → refuse), never a read error.
fn contains_marker(bytes: &[u8]) -> bool {
    let marker = GENERATED_MARKER.as_bytes();
    bytes.windows(marker.len()).any(|window| window == marker)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rule_doc(tag: &str) -> String {
        format!(
            "+++\n\
             tag = \"{tag}\"\n\
             title = \"t\"\n\
             error_class = \"e\"\n\
             home = {{ kind = \"global\" }}\n\
             created = \"2026-01-01\"\n\
             status = {{ kind = \"active\" }}\n\
             incident = \"i\"\n\
             +++\n\n\
             Body.\n"
        )
    }

    #[test]
    fn loads_md_files_in_sorted_order_ignoring_others() {
        let dir = tempfile::tempdir().expect("tempdir");
        fs::write(dir.path().join("b.md"), rule_doc("R:beta")).expect("write b");
        fs::write(dir.path().join("a.md"), rule_doc("R:alpha")).expect("write a");
        fs::write(dir.path().join("notes.txt"), "not a rule").expect("write notes");

        let library = load_rules(dir.path()).expect("load succeeds");
        let validated = library.validate().expect("distinct tags validate");
        assert_eq!(validated.len(), 2);
        // Sorted by file name: a.md (R:alpha) before b.md (R:beta).
        assert_eq!(validated.rules()[0].tag().as_str(), "R:alpha");
        assert_eq!(validated.rules()[1].tag().as_str(), "R:beta");
    }

    #[test]
    fn a_bad_file_stops_the_load_and_names_it() {
        let dir = tempfile::tempdir().expect("tempdir");
        fs::write(dir.path().join("ok.md"), rule_doc("R:ok")).expect("write ok");
        fs::write(dir.path().join("broken.md"), "not a rule at all").expect("write broken");

        match load_rules(dir.path()) {
            Err(LoadError::Parse { path, .. }) => assert!(path.ends_with("broken.md")),
            other => panic!("expected a Parse error naming broken.md, got {other:?}"),
        }
    }

    #[test]
    fn missing_directory_is_a_readdir_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        let missing = dir.path().join("does-not-exist");
        assert!(matches!(
            load_rules(&missing),
            Err(LoadError::ReadDir { .. })
        ));
    }

    #[test]
    fn empty_directory_loads_an_empty_library() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = load_rules(dir.path()).expect("load succeeds");
        assert!(library.validate().expect("validate").is_empty());
    }

    // --- write side -------------------------------------------------------

    use crate::emit::{OutputFile, RelativePath};
    use crate::rule::RuleTag;

    fn output(segments: &[&str], body: &str, tags: &[&str]) -> OutputFile {
        let sources = tags
            .iter()
            .map(|t| RuleTag::parse(*t).expect("valid tag"))
            .collect();
        OutputFile::new(
            RelativePath::from_segments(segments),
            body.to_owned(),
            sources,
        )
    }

    #[test]
    fn writes_files_creating_parent_dirs_and_appends_the_header() {
        let dir = tempfile::tempdir().expect("tempdir");
        let files = vec![output(
            &["skills", "global", "SKILL.md"],
            "hello body\n",
            &["R:a"],
        )];

        let written = write_all(dir.path(), &files).expect("write succeeds");
        assert_eq!(written, 1);

        let on_disk =
            fs::read_to_string(dir.path().join("skills/global/SKILL.md")).expect("read back");
        assert!(
            on_disk.starts_with("hello body\n"),
            "body preserved verbatim"
        );
        assert!(
            on_disk.contains(GENERATED_MARKER),
            "carries the generated-by marker"
        );
        assert!(on_disk.contains("rules=R:a"), "records provenance");
        assert!(on_disk.contains("sha256="), "records the content hash");
    }

    #[test]
    fn refuses_to_clobber_a_file_lacking_the_marker() {
        let dir = tempfile::tempdir().expect("tempdir");
        let target = dir.path().join("skills/global/SKILL.md");
        fs::create_dir_all(target.parent().expect("has parent")).expect("mkdir");
        fs::write(&target, "human authored, precious\n").expect("seed human file");

        let files = vec![output(
            &["skills", "global", "SKILL.md"],
            "generated\n",
            &["R:a"],
        )];
        match write_all(dir.path(), &files) {
            Err(WriteError::WouldClobberUnversioned { path }) => {
                assert!(path.ends_with("SKILL.md"));
            }
            other => panic!("expected a clobber refusal, got {other:?}"),
        }
        assert_eq!(
            fs::read_to_string(&target).expect("read back"),
            "human authored, precious\n",
            "the human file is left untouched"
        );
    }

    #[test]
    fn overwrites_a_file_it_previously_generated() {
        let dir = tempfile::tempdir().expect("tempdir");
        let first = vec![output(&["skills", "global", "SKILL.md"], "v1\n", &["R:a"])];
        write_all(dir.path(), &first).expect("first write succeeds");

        let second = vec![output(&["skills", "global", "SKILL.md"], "v2\n", &["R:a"])];
        let written = write_all(dir.path(), &second)
            .expect("second write succeeds — the file carries our marker");
        assert_eq!(written, 1);

        let on_disk =
            fs::read_to_string(dir.path().join("skills/global/SKILL.md")).expect("read back");
        assert!(on_disk.starts_with("v2\n"));
        assert!(
            !on_disk.contains("v1"),
            "regeneration replaces the old body"
        );
    }

    #[test]
    fn a_single_conflict_aborts_the_whole_write() {
        let dir = tempfile::tempdir().expect("tempdir");
        // Pre-seed a human file at the SECOND target only.
        let human = dir.path().join("b/human.md");
        fs::create_dir_all(human.parent().expect("has parent")).expect("mkdir");
        fs::write(&human, "precious\n").expect("seed human file");

        let files = vec![
            output(&["a", "gen.md"], "safe\n", &["R:a"]),
            output(&["b", "human.md"], "would clobber\n", &["R:b"]),
        ];
        assert!(matches!(
            write_all(dir.path(), &files),
            Err(WriteError::WouldClobberUnversioned { .. })
        ));
        assert!(
            !dir.path().join("a/gen.md").exists(),
            "pre-flight aborts before any file is written — no half-generated tree"
        );
        assert_eq!(
            fs::read_to_string(&human).expect("read back"),
            "precious\n",
            "the human file is left untouched"
        );
    }

    #[test]
    fn rewriting_the_same_files_is_byte_identical() {
        let dir = tempfile::tempdir().expect("tempdir");
        let files = vec![output(
            &["skills", "global", "SKILL.md"],
            "stable body\n",
            &["R:a"],
        )];

        write_all(dir.path(), &files).expect("first write");
        let first = fs::read(dir.path().join("skills/global/SKILL.md")).expect("read after first");
        write_all(dir.path(), &files).expect("second write regenerates our own file");
        let second =
            fs::read(dir.path().join("skills/global/SKILL.md")).expect("read after second");

        assert_eq!(
            first, second,
            "rebuilding unchanged input produces byte-identical output (header hash included)"
        );
    }

    // --- verify side ------------------------------------------------------

    #[test]
    fn parse_generated_recovers_the_exact_body_and_hash() {
        // A body that itself ends in a newline — the common case — round-trips.
        let file = output(&["AGENTS.md"], "line one\nline two\n", &["R:a"]);
        let rendered = render_with_header(&file);
        let (body, hash) = parse_generated(&rendered).expect("a rendered file parses");
        assert_eq!(body, "line one\nline two\n", "body recovered verbatim");
        assert_eq!(
            hash,
            sha256_hex("line one\nline two\n".as_bytes()),
            "the recorded hash is the body hash"
        );
    }

    #[test]
    fn parse_generated_handles_a_body_without_a_trailing_newline() {
        let file = output(&["AGENTS.md"], "no trailing newline", &["R:a"]);
        let rendered = render_with_header(&file);
        let (body, hash) = parse_generated(&rendered).expect("parses");
        assert_eq!(body, "no trailing newline");
        assert_eq!(hash, sha256_hex("no trailing newline".as_bytes()));
    }

    #[test]
    fn parse_generated_rejects_a_file_without_the_marker() {
        assert!(parse_generated("just some text\nno marker here\n").is_none());
    }

    #[test]
    fn verify_reports_ok_for_a_freshly_written_file_and_missing_when_absent() {
        let dir = tempfile::tempdir().expect("tempdir");
        let files = vec![output(&["AGENTS.md"], "body\n", &["R:a"])];

        // Before any write: the expected file is Missing.
        let before = verify_all(dir.path(), &files).expect("verify reads");
        assert_eq!(*before[0].status(), VerifyStatus::Missing);

        // After write: Ok.
        write_all(dir.path(), &files).expect("write");
        let after = verify_all(dir.path(), &files).expect("verify reads");
        assert_eq!(*after[0].status(), VerifyStatus::Ok);
        assert_eq!(after[0].path().as_str(), "AGENTS.md");
    }

    #[test]
    fn an_orphaned_fixed_target_is_reported() {
        let dir = tempfile::tempdir().expect("tempdir");
        // Generate AGENTS.md, then verify against an EMPTY expected set — as if
        // the library were emptied, so `build` emits no AGENTS.md while the
        // marked one lingers.
        write_all(
            dir.path(),
            &[output(&["AGENTS.md"], "agents body\n", &["R:p"])],
        )
        .expect("write");
        let reports = verify_all(dir.path(), &[]).expect("verify reads");
        assert_eq!(reports.len(), 1);
        assert_eq!(*reports[0].status(), VerifyStatus::Orphan);
        assert_eq!(reports[0].path().as_str(), "AGENTS.md");
    }

    #[test]
    fn an_orphaned_project_layer_file_is_reported() {
        let dir = tempfile::tempdir().expect("tempdir");
        // `.claude/rules/` is an owned *directory*: deleting the last rule of a
        // project home must strand its layer file as an orphan, exactly as a
        // deleted rule strands its `.cursor/rules/*.mdc`.
        write_all(
            dir.path(),
            &[output(
                &[".claude", "rules", "project-gone.md"],
                "project body\n",
                &["R:p"],
            )],
        )
        .expect("write");
        let reports = verify_all(dir.path(), &[]).expect("verify reads");
        assert_eq!(reports.len(), 1);
        assert_eq!(*reports[0].status(), VerifyStatus::Orphan);
        assert_eq!(reports[0].path().as_str(), ".claude/rules/project-gone.md");
    }

    /// The regression pin for the collision fixed on 2026-08-22: a hand-authored
    /// repository-root `CLAUDE.md` is not a relearn-owned path, so the orphan
    /// scan must not look at it and `verify` must not classify it at all. Before
    /// the fix, bare `verify` reported it `Unversioned` and exited non-zero on a
    /// clean tree.
    #[test]
    fn a_hand_authored_root_claude_md_is_never_claimed() {
        let dir = tempfile::tempdir().expect("tempdir");
        std::fs::write(
            dir.path().join("CLAUDE.md"),
            "# Hand-authored charter\n\nThe recreation standard lives here.\n",
        )
        .expect("write the charter");
        let reports = verify_all(dir.path(), &[]).expect("verify reads");
        assert!(
            reports.is_empty(),
            "the hand-authored project charter is not relearn's to police: {reports:?}"
        );
    }

    #[test]
    fn a_marked_file_outside_owned_locations_is_not_scanned() {
        let dir = tempfile::tempdir().expect("tempdir");
        // A marker-bearing file somewhere relearn does NOT emit to. The ownership
        // policy scopes the orphan scan to owned locations, so this is left alone
        // even though it carries the marker.
        write_all(
            dir.path(),
            &[output(&["notes", "stray.md"], "body\n", &["R:x"])],
        )
        .expect("write");
        let reports = verify_all(dir.path(), &[]).expect("verify reads");
        assert!(
            reports.is_empty(),
            "a marked file outside skills/ .cursor/rules/ and the fixed targets is not relearn's to police: {reports:?}"
        );
    }
}
