//! `fsio` — all filesystem reads (loading `rules/*.md`) and writes (emitting
//! target files), including the generated-file guard that refuses to overwrite
//! a target lacking the generated-by header and matching hash
//! (`[R:generate-guards-unversioned]`).
//!
//! **Must NOT:** contain business logic. It moves bytes and prepends file names
//! to diagnostics; every decision about *what* a document means is made in
//! `rule` (parsing) and every decision about *what* to write is made in `emit`.

use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

use crate::emit::OutputFile;
use crate::library::{Library, Unvalidated};
use crate::rule::{ParseError, parse_document};

/// The opening of the generated-by comment. Its presence in an existing file is
/// how the overwrite guard tells "relearn wrote this" from "a human wrote this":
/// a file carrying it may be regenerated; a file lacking it is never clobbered
/// (`[R:generate-guards-unversioned]`). An HTML comment is valid in every
/// current target (all markdown-family) and, placed after the body, never
/// disturbs the leading YAML front-matter of a skill or `.mdc`.
const GENERATED_MARKER: &str = "<!-- relearn:generated";

/// Why loading a rules directory failed. Every variant names the file (or
/// directory) at fault, so a diagnostic points the operator straight at it.
#[derive(Debug, thiserror::Error)]
pub enum LoadError {
    /// The rules directory could not be read.
    #[error("reading directory {path:?}: {source}")]
    ReadDir {
        /// The directory that could not be read.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A rule file could not be read.
    #[error("reading {path:?}: {source}")]
    Io {
        /// The file that could not be read.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A rule file was read but did not parse. Carries the field-level
    /// `ParseError` and the file it came from — the "file + field" diagnostic.
    #[error("{path:?}: {source}")]
    Parse {
        /// The file that failed to parse.
        path: PathBuf,
        /// The field-level parse error.
        #[source]
        source: ParseError,
    },
}

/// Load every `*.md` file in `dir` into an unvalidated library, in sorted file
/// order for determinism. A file that cannot be read or parsed stops the load
/// with a diagnostic naming it — a bad file is never silently skipped.
///
/// The result is `Library<Unvalidated>`; the caller runs `validate` to check
/// cross-file invariants (tag uniqueness) and reach `Library<Validated>`.
pub fn load_rules(dir: &Path) -> Result<Library<Unvalidated>, LoadError> {
    let read = fs::read_dir(dir).map_err(|source| LoadError::ReadDir {
        path: dir.to_path_buf(),
        source,
    })?;

    let mut paths: Vec<PathBuf> = Vec::new();
    for entry in read {
        let entry = entry.map_err(|source| LoadError::ReadDir {
            path: dir.to_path_buf(),
            source,
        })?;
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "md") {
            paths.push(path);
        }
    }
    paths.sort();

    let mut library = Library::new();
    for path in paths {
        // `path` is moved into the error on either failure path and dropped on
        // success — so it is never cloned.
        let content = match fs::read_to_string(&path) {
            Ok(content) => content,
            Err(source) => return Err(LoadError::Io { path, source }),
        };
        let rule = match parse_document(&content) {
            Ok(rule) => rule,
            Err(source) => return Err(LoadError::Parse { path, source }),
        };
        library.push(rule);
    }
    Ok(library)
}

/// Why writing emitted files failed. Every variant names the file at fault.
#[derive(Debug, thiserror::Error)]
pub enum WriteError {
    /// A parent directory could not be created.
    #[error("creating directory {path:?}: {source}")]
    CreateDir {
        /// The directory that could not be created.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// A file could not be read (during the pre-flight check) or written.
    #[error("{path:?}: {source}")]
    Io {
        /// The file at fault.
        path: PathBuf,
        /// The underlying I/O error.
        #[source]
        source: std::io::Error,
    },
    /// The target file already exists and does not carry relearn's generated-by
    /// marker, so it is unversioned, human-authored content. The guard refuses
    /// to overwrite it rather than destroy a correction that was never a rule.
    #[error(
        "{path:?} exists but was not generated by relearn (no generated-by marker); refusing to overwrite unversioned content"
    )]
    WouldClobberUnversioned {
        /// The file that would have been clobbered.
        path: PathBuf,
    },
}

/// Write every emitted file under `out_dir`, each with its generated-by header
/// and content hash appended.
///
/// All-or-nothing over the clobber guard: a **pre-flight** pass checks every
/// target first, and if any existing target lacks the generated-by marker the
/// whole write aborts with [`WriteError::WouldClobberUnversioned`] before a
/// single byte is written — so one human-authored collision never leaves a
/// half-generated tree. Returns the number of files written.
#[must_use = "the write result reports failure (clobber refusal, I/O); ignoring it discards that"]
pub fn write_all(out_dir: &Path, files: &[OutputFile]) -> Result<usize, WriteError> {
    // Pre-flight: refuse the entire write if any target is unversioned content.
    for file in files {
        let target = out_dir.join(file.path().as_str());
        match fs::read(&target) {
            Ok(existing) => {
                if !contains_marker(&existing) {
                    return Err(WriteError::WouldClobberUnversioned { path: target });
                }
            }
            // Absent target is the normal case — it will be created below.
            Err(source) if source.kind() == ErrorKind::NotFound => {}
            Err(source) => {
                return Err(WriteError::Io {
                    path: target,
                    source,
                });
            }
        }
    }

    // Commit: every target is either new or one we previously generated.
    for file in files {
        let target = out_dir.join(file.path().as_str());
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent).map_err(|source| WriteError::CreateDir {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        let rendered = render_with_header(file);
        fs::write(&target, rendered).map_err(|source| WriteError::Io {
            path: target,
            source,
        })?;
    }
    Ok(files.len())
}

/// Append the generated-by header (marker, tool version, source-rule tags, and
/// the `sha256` of the body) to a file's body. The hash covers the body only —
/// not the header — so it can later be recomputed and compared to detect a hand
/// edit of a generated file.
fn render_with_header(file: &OutputFile) -> String {
    let hash = sha256_hex(file.contents().as_bytes());
    let rules = file
        .sources()
        .iter()
        .map(|tag| tag.as_str())
        .collect::<Vec<_>>()
        .join(",");
    // ASCII-only: this marker is embedded into every emitted file and parsed by
    // several downstream tools; it must not depend on their encoding assumptions.
    let header = format!(
        "{GENERATED_MARKER} v{version} sha256={hash} rules={rules} -- DO NOT EDIT; regenerate with `relearn build` -->",
        version = env!("CARGO_PKG_VERSION"),
    );
    format!("{body}\n{header}\n", body = file.contents())
}

/// Hex-encode the SHA-256 of `bytes`.
fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}

/// Whether `bytes` contains the generated-by marker anywhere. Byte-level (not
/// UTF-8) so a non-text or invalid-UTF-8 existing file is simply treated as
/// unversioned (marker absent → refuse), never a read error.
fn contains_marker(bytes: &[u8]) -> bool {
    let marker = GENERATED_MARKER.as_bytes();
    bytes.windows(marker.len()).any(|window| window == marker)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rule_doc(tag: &str) -> String {
        format!(
            "+++\n\
             tag = \"{tag}\"\n\
             title = \"t\"\n\
             error_class = \"e\"\n\
             home = {{ kind = \"global\" }}\n\
             created = \"2026-01-01\"\n\
             status = {{ kind = \"active\" }}\n\
             incident = \"i\"\n\
             +++\n\n\
             Body.\n"
        )
    }

    #[test]
    fn loads_md_files_in_sorted_order_ignoring_others() {
        let dir = tempfile::tempdir().expect("tempdir");
        fs::write(dir.path().join("b.md"), rule_doc("R:beta")).expect("write b");
        fs::write(dir.path().join("a.md"), rule_doc("R:alpha")).expect("write a");
        fs::write(dir.path().join("notes.txt"), "not a rule").expect("write notes");

        let library = load_rules(dir.path()).expect("load succeeds");
        let validated = library.validate().expect("distinct tags validate");
        assert_eq!(validated.len(), 2);
        // Sorted by file name: a.md (R:alpha) before b.md (R:beta).
        assert_eq!(validated.rules()[0].tag().as_str(), "R:alpha");
        assert_eq!(validated.rules()[1].tag().as_str(), "R:beta");
    }

    #[test]
    fn a_bad_file_stops_the_load_and_names_it() {
        let dir = tempfile::tempdir().expect("tempdir");
        fs::write(dir.path().join("ok.md"), rule_doc("R:ok")).expect("write ok");
        fs::write(dir.path().join("broken.md"), "not a rule at all").expect("write broken");

        match load_rules(dir.path()) {
            Err(LoadError::Parse { path, .. }) => assert!(path.ends_with("broken.md")),
            other => panic!("expected a Parse error naming broken.md, got {other:?}"),
        }
    }

    #[test]
    fn missing_directory_is_a_readdir_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        let missing = dir.path().join("does-not-exist");
        assert!(matches!(
            load_rules(&missing),
            Err(LoadError::ReadDir { .. })
        ));
    }

    #[test]
    fn empty_directory_loads_an_empty_library() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = load_rules(dir.path()).expect("load succeeds");
        assert!(library.validate().expect("validate").is_empty());
    }

    // --- write side -------------------------------------------------------

    use crate::emit::{OutputFile, RelativePath};
    use crate::rule::RuleTag;

    fn output(segments: &[&str], body: &str, tags: &[&str]) -> OutputFile {
        let sources = tags
            .iter()
            .map(|t| RuleTag::parse(*t).expect("valid tag"))
            .collect();
        OutputFile::new(
            RelativePath::from_segments(segments),
            body.to_owned(),
            sources,
        )
    }

    #[test]
    fn writes_files_creating_parent_dirs_and_appends_the_header() {
        let dir = tempfile::tempdir().expect("tempdir");
        let files = vec![output(
            &["skills", "global", "SKILL.md"],
            "hello body\n",
            &["R:a"],
        )];

        let written = write_all(dir.path(), &files).expect("write succeeds");
        assert_eq!(written, 1);

        let on_disk =
            fs::read_to_string(dir.path().join("skills/global/SKILL.md")).expect("read back");
        assert!(
            on_disk.starts_with("hello body\n"),
            "body preserved verbatim"
        );
        assert!(
            on_disk.contains(GENERATED_MARKER),
            "carries the generated-by marker"
        );
        assert!(on_disk.contains("rules=R:a"), "records provenance");
        assert!(on_disk.contains("sha256="), "records the content hash");
    }

    #[test]
    fn refuses_to_clobber_a_file_lacking_the_marker() {
        let dir = tempfile::tempdir().expect("tempdir");
        let target = dir.path().join("skills/global/SKILL.md");
        fs::create_dir_all(target.parent().expect("has parent")).expect("mkdir");
        fs::write(&target, "human authored, precious\n").expect("seed human file");

        let files = vec![output(
            &["skills", "global", "SKILL.md"],
            "generated\n",
            &["R:a"],
        )];
        match write_all(dir.path(), &files) {
            Err(WriteError::WouldClobberUnversioned { path }) => {
                assert!(path.ends_with("SKILL.md"));
            }
            other => panic!("expected a clobber refusal, got {other:?}"),
        }
        assert_eq!(
            fs::read_to_string(&target).expect("read back"),
            "human authored, precious\n",
            "the human file is left untouched"
        );
    }

    #[test]
    fn overwrites_a_file_it_previously_generated() {
        let dir = tempfile::tempdir().expect("tempdir");
        let first = vec![output(&["skills", "global", "SKILL.md"], "v1\n", &["R:a"])];
        write_all(dir.path(), &first).expect("first write succeeds");

        let second = vec![output(&["skills", "global", "SKILL.md"], "v2\n", &["R:a"])];
        let written = write_all(dir.path(), &second)
            .expect("second write succeeds — the file carries our marker");
        assert_eq!(written, 1);

        let on_disk =
            fs::read_to_string(dir.path().join("skills/global/SKILL.md")).expect("read back");
        assert!(on_disk.starts_with("v2\n"));
        assert!(
            !on_disk.contains("v1"),
            "regeneration replaces the old body"
        );
    }

    #[test]
    fn a_single_conflict_aborts_the_whole_write() {
        let dir = tempfile::tempdir().expect("tempdir");
        // Pre-seed a human file at the SECOND target only.
        let human = dir.path().join("b/human.md");
        fs::create_dir_all(human.parent().expect("has parent")).expect("mkdir");
        fs::write(&human, "precious\n").expect("seed human file");

        let files = vec![
            output(&["a", "gen.md"], "safe\n", &["R:a"]),
            output(&["b", "human.md"], "would clobber\n", &["R:b"]),
        ];
        assert!(matches!(
            write_all(dir.path(), &files),
            Err(WriteError::WouldClobberUnversioned { .. })
        ));
        assert!(
            !dir.path().join("a/gen.md").exists(),
            "pre-flight aborts before any file is written — no half-generated tree"
        );
        assert_eq!(
            fs::read_to_string(&human).expect("read back"),
            "precious\n",
            "the human file is left untouched"
        );
    }
}
